### GET request to example server
GET http://rufinder.savagedomain.net/api/posts/
Accept: application/json

### Register
POST https://rufinder.savagedomain.net/api/users/register/
Content-Type: application/json

{
  "username": "testuser889",
  "email": "testuser@gmail.com",
  "password": "testpassword123",
  "first_name":"Test",
  "last_name": "User",
  "display_name": "Test Userz"
}

### Login to get JWT tokens
POST https://rufinder.savagedomain.net/api/users/token/
Content-Type: application/json

{
  "username": "testuser889",
  "password": "testpassword123"
}

> {%
    client.global.set("access", response.body.access);
    client.global.set("refresh", response.body.refresh);
 %}

### Create a new post
POST http://rufinder.savagedomain.net/api/posts/
Authorization: Bearer {{access}}
Content-Type: application/json

{
  "title": "Lost Wallet",
  "description": "Brown Leather Wallet",
  "category": "L",
  "location": "Campus Center"
}

> {% client.global.set("post_id", response.body.id) %}

### Add comment to post
POST http://rufinder.savagedomain.net/api/comments/
Authorization: Bearer {{access}}
Content-Type: application/json

{
  "post": {{post_id}},
  "body": "This is a test comment!"
}