@base = https://rufinder.savagedomain.net
@api = {{base}}/api

### List posts (public)
GET {{api}}/posts/
Accept: application/json


### Register (run once; change username/email if they already exist)
POST {{api}}/users/register/
Content-Type: application/json
Accept: application/json

{
  "username": "testuser889",
  "email": "testuser@gmail.com",
  "password": "testpassword123",
  "first_name": "Test",
  "last_name": "User",
  "display_name": "Test Userz"
}


### Login
# @name login
POST {{api}}/users/token/
Content-Type: application/json
Accept: application/json

{
  "username": "testuser889",
  "password": "testpassword123"
}

### Create post (uses access from the previous response)
POST {{api}}/posts/
Authorization: Bearer {{login.response.body.$.access}}
Content-Type: application/json
Accept: application/json

{
  "title": "Lost Wallet",
  "description": "Brown Leather Wallet",
  "category": "L",
  "location": "Campus Center"
}

### Add comment (uses the same access)
POST {{api}}/comments/
Authorization: Bearer {{login.response.body.$.access}}
Content-Type: application/json
Accept: application/json

{
  "post": 1,
  "body": "This is a test comment!"
}
